### ISSUE TITLE
Hi general question

### ISSUE THREAD

**Issue by Codepulze** [NotKatsu/GoSearch#1]
I started learning gofile, do you think its worth learning it? or just general opinion on it, it seems like cool languge but i dont think ill use it but i started already learning soo :DD

**Comment by Codepulze** [comment]
also your projects are cool :)

**Comment by NotKatsu** [comment]
Hey @Codepulze, Thanks alot i appreciate it, 
GoSearch is not even close to being done yet but i ensure you at some point it will get finished, ive already finished the GUI and its looking pretty sweet so expect the README to be updated soon with some screenshots etc.

**Comment by Codepulze** [comment]
np underrated developer, keep going ! <3
